services:
  chinese-checkers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chinese-checkers-dev-instance
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go run cmd/chinese-checkers/main.go && tail -f /dev/null"
    tty: true
    environment:
      - GOFLAGS=-buildvcs=false
