name: Build and deploy admin

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the admin panel to be deployed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build
        env:
          VITE_POSTGREST_URL: https://${{ vars.DEPLOY_SERVER_NAME }}/postgrest
        run: make build-admin-panel
        
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: admin/dist/
  
  deploy:
    name: Deploy the admin panel to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy artifact to GitHub pages
        uses: actions/deploy-pages@v4
