name: Go

on: [push]

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install
        run: make install
          
      - name: Lint
        run: make lint

      - name: Vet
        run: make vet

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install
        run: make install
          
      - name: Build
        run: make build-cli && make build-api
        
      - name: Run the web app and test it
        run: make start-web-app-dev && make test && make down

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Enable corepack to use latest stable yarn
        run: corepack enable
      - name: Install playwright dependencies
        run: make install-e2e
      - name: Run the web app and run e2e tests
        run: make start-web-app && make test-e2e && make down
        
